(assert (= 42 42))
(assert (= 42 42.0))

(assert (number? 42))
(assert (not (number? #t)))
;(assert (complex? 2+3i))
;(assert (not (real? 2+3i)))
(assert (real? 3.1416))
(assert (real? 22/7))
(assert (real? 42))
;(assert (not (rational? 2+3i)))
;(assert (not (rational? 3.1416)))
;(assert (rational? 22/7))
(assert (not (integer? 22/7)))
(assert (integer? 42))

(assert (zero? 0))
(assert (not (zero? 1)))
(assert (odd? 1))
(assert (not (odd? 2)))
(assert (even? 6))
(assert (not (even? 7)))
(assert (positive? 5))
(assert (not (positive? -4)))
(assert (negative? -13))
(assert (not (negative? 0)))

(assert-equal 9 (max 8 2 7 3 9 5))
(assert-equal 2 (min 8 2 7 3 9 5))

